[package]
name = "rab"
version = "0.1.3"
authors = ["ityt <imran.tierce@protonmail.com>"]
edition = "2018"
repository = "https://github.com/itytophile/rab"
description = "Rusty Armor Builds - Monster Hunter Rise Armor Set Creation Tool"
license = "GPL-3.0"
keywords = ["monster", "hunter", "rise", "armor", "search"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
ron = "0.6"
iced = "0.3"
itertools = "0.10"
once_cell = "1.7"
lexical-sort = "0.3"