[package]
name = "rab"
version = "0.1.0"
authors = ["ityt <imran.tierce@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
ron = "0.6"
iced = "0.3"