[package]
name = "rab"
version = "0.1.1"
authors = ["ityt <imran.tierce@protonmail.com>"]
edition = "2018"
repository = "https://github.com/itytophile/rab"
description = "Rusty Armor Builds - Monster Hunter Rise Armor Set Creation Tool"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
ron = "0.6"
iced = "0.3"
itertools = "0.10"
